(() => {
  const TYPES={
    federal:{label:'Federal — RFB/PGFN',portal:'https://solucoes.receita.fazenda.gov.br/Servicos/certidaointernet/PJ/Emitir'},
    fgts:{label:'FGTS — CRF Caixa',portal:'https://consulta-crf.caixa.gov.br/consultacrf/pages/consultaEmpregador.jsf'},
    cndt:{label:'CNDT — Justiça do Trabalho',portal:'https://cndt-certidao.tst.jus.br/inicio.faces'},
    estadual:{label:'Estadual — SEFAZ/PGE',portal:'https://www.dividaativa.pge.sp.gov.br/sc/pages/crda/emitirCrda.jsf'},
    municipal:{label:'Municipal',portal:'https://egov.santos.sp.gov.br/tribusweb/CertidaoGeral/Certidao'}
  };
  const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const db=()=>window.atlasAuth?.client;
  const digits=v=>String(v||'').replace(/\D/g,'');
  const fmtDate=v=>{if(!v)return '—';const d=new Date(v+'T12:00:00');return Number.isNaN(d.getTime())?'—':d.toLocaleDateString('pt-BR')};
  const daysTo=v=>{if(!v)return null;const a=new Date();a.setHours(0,0,0,0);const b=new Date(v+'T12:00:00');return Math.ceil((b-a)/86400000)};
  const label={valid:'Válida',warning:'A vencer',expired:'Vencida',irregular:'Irregular',pending:'Pendente',error:'Erro'};
  function status(r){const d=daysTo(r.expires_at);if(r.status==='irregular')return'irregular';if(r.status==='error')return'error';if(d!==null&&d<0)return'expired';if(d!==null&&d<=30)return'warning';if(r.status==='valid'||(d!==null&&d>30))return'valid';return'pending'}
  function head(){const q=(s,t)=>{const e=document.querySelector(s);if(e)e.textContent=t};q('#page-title','Certidões');q('#page-kicker','GESTÃO');q('#page-desc','Regularidade fiscal, trabalhista e cadastral das empresas monitoradas.')}
  async function load(){const c=db();if(!c)return{companies:[],certs:[]};const [{data:companies,error:e1},{data:certs,error:e2}]=await Promise.all([c.from('clients').select('id,legal_name,tax_id,city,state').is('deleted_at',null).order('legal_name'),c.from('atlas_certificates').select('*').order('expires_at',{ascending:true,nullsFirst:false})]);if(e1||e2)throw(e1||e2);return{companies:companies||[],certs:certs||[]}}
  function metrics(rows){const m={valid:0,warning:0,expired:0,irregular:0,pending:0,error:0};for(const r of rows)m[status(r)]++;return m}
  const kpi=(t,n,k)=>`<div class="cert-kpi"><span>${t}</span><strong data-cert-kpi="${k}">${n}</strong></div>`;
  function row(r,c){const s=status(r);return `<tr data-company="${r.client_id}" data-status="${s}"><td data-label="Empresa"><strong>${esc(c?.legal_name||'Empresa')}</strong><div class="cert-note">${esc(c?.tax_id||'')}</div></td><td data-label="Certidão">${esc(TYPES[r.cert_type]?.label||r.cert_type)}</td><td data-label="Status"><span class="cert-status ${s}">${label[s]}</span>${s==='warning'?`<div class="cert-note">${daysTo(r.expires_at)} dia(s)</div>`:''}</td><td data-label="Emissão">${fmtDate(r.issued_at)}</td><td data-label="Validade">${fmtDate(r.expires_at)}</td><td data-label="Última consulta">${r.last_checked_at?new Date(r.last_checked_at).toLocaleString('pt-BR'):'—'}</td><td data-label="Fonte">${esc(r.source||'—')}</td><td data-label="Ações"><div class="cert-actions"><button class="cert-btn primary" data-cert-check="${r.id}">Consultar agora</button><button class="cert-btn" data-cert-edit="${r.id}">Registrar</button>${r.pdf_url?`<a class="cert-btn" href="${esc(r.pdf_url)}" target="_blank" rel="noopener">PDF</a>`:''}</div></td></tr>`}
  function dialog(){return `<dialog id="cert-dialog" class="cert-dialog"><form method="dialog" class="cert-form"><h2 style="margin-top:0">Registrar certidão</h2><input type="hidden" id="cert-id"><div class="cert-form-grid"><div><label>Status</label><select id="cert-status"><option value="valid">Válida</option><option value="irregular">Irregular</option><option value="pending">Pendente</option><option value="error">Erro</option></select></div><div><label>Número / código</label><input id="cert-code"></div><div><label>Emissão</label><input id="cert-issued" type="date"></div><div><label>Validade</label><input id="cert-expires" type="date"></div><div class="full"><label>URL/PDF</label><input id="cert-pdf" type="url"></div><div class="full"><label>Observações</label><textarea id="cert-notes" rows="3"></textarea></div></div><div class="cert-dialog-actions"><button value="cancel" class="cert-btn">Cancelar</button><button id="cert-save" value="default" class="cert-btn primary">Salvar</button></div></form></dialog>`}
  async function render(){head();const holder=document.querySelector('#page-content');if(!holder)return;holder.innerHTML='<div class="surface pad">Carregando certidões...</div>';try{const{companies,certs}=await load();const cmap=new Map(companies.map(c=>[c.id,c]));const m=metrics(certs);holder.innerHTML=`<div class="cert-kpis">${kpi('Válidas',m.valid,'valid')}${kpi('A vencer',m.warning,'warning')}${kpi('Vencidas',m.expired,'expired')}${kpi('Irregulares',m.irregular,'irregular')}${kpi('Pendentes/erro',m.pending+m.error,'pending')}</div><section class="surface pad"><div class="cert-toolbar"><div><h2 style="margin:0">Matriz de certidões</h2><div class="cert-note">Alertas operacionais em 30, 15 e 7 dias antes do vencimento.</div></div><div class="cert-filters"><select id="cert-company" class="cert-btn"><option value="">Todas as empresas</option>${companies.map(c=>`<option value="${c.id}">${esc(c.legal_name)}</option>`).join('')}</select><select id="cert-status-filter" class="cert-btn"><option value="">Todos os status</option>${Object.entries(label).map(([k,v])=>`<option value="${k}">${v}</option>`).join('')}</select><button id="cert-refresh-all" class="cert-btn primary">Atualizar todas</button></div></div><div class="cert-table-wrap"><table class="cert-table"><thead><tr><th>Empresa</th><th>Certidão</th><th>Status</th><th>Emissão</th><th>Validade</th><th>Última consulta</th><th>Fonte</th><th>Ações</th></tr></thead><tbody id="cert-body">${certs.map(r=>row(r,cmap.get(r.client_id))).join('')}</tbody></table></div></section>${dialog()}`;bind(certs,cmap)}catch(e){holder.innerHTML=`<div class="surface pad">Não foi possível carregar o módulo de certidões: ${esc(e?.message||e)}</div>`}}
  function bind(rows,cmap){const byId=new Map(rows.map(r=>[r.id,r]));const filter=()=>{const c=document.querySelector('#cert-company')?.value||'';const s=document.querySelector('#cert-status-filter')?.value||'';document.querySelectorAll('#cert-body tr').forEach(tr=>tr.hidden=!!((c&&tr.dataset.company!==c)||(s&&tr.dataset.status!==s)))};document.querySelector('#cert-company')?.addEventListener('change',filter);document.querySelector('#cert-status-filter')?.addEventListener('change',filter);document.querySelector('#cert-refresh-all')?.addEventListener('click',async e=>{const b=e.currentTarget;b.disabled=true;b.textContent='Consultando...';for(const r of rows)await check(r,cmap.get(r.client_id),false);b.disabled=false;b.textContent='Atualizar todas';await render()});document.querySelector('#cert-body')?.addEventListener('click',async e=>{const a=e.target.closest('[data-cert-check]');if(a){a.disabled=true;const r=byId.get(a.dataset.certCheck);await check(r,cmap.get(r?.client_id),true);await render();return}const ed=e.target.closest('[data-cert-edit]');if(ed)openEdit(byId.get(ed.dataset.certEdit))});document.querySelector('#cert-save')?.addEventListener('click',async e=>{e.preventDefault();await save();document.querySelector('#cert-dialog')?.close();await render()})}
  async function check(r,c,interactive){if(!r||!c)return;const api=await fetch(`/api/certificates?type=${encodeURIComponent(r.cert_type)}&cnpj=${digits(c.tax_id)}&uf=${encodeURIComponent(c.state||'SP')}&city=${encodeURIComponent(c.city||'')}`,{cache:'no-store'});const out=await api.json();await db().from('atlas_certificates').update({last_checked_at:new Date().toISOString(),source:out.source||r.source,metadata:{...(r.metadata||{}),connector:out}}).eq('id',r.id);if(interactive&&out.portal)window.open(out.portal,'_blank','noopener');if(interactive&&out.message)alert(out.message)}
  function openEdit(r){const q=s=>document.querySelector(s);q('#cert-id').value=r.id;q('#cert-status').value=r.status||'pending';q('#cert-code').value=r.certificate_number||'';q('#cert-issued').value=r.issued_at||'';q('#cert-expires').value=r.expires_at||'';q('#cert-pdf').value=r.pdf_url||'';q('#cert-notes').value=r.notes||'';q('#cert-dialog').showModal()}
  async function save(){const q=s=>document.querySelector(s);await db().from('atlas_certificates').update({status:q('#cert-status').value,certificate_number:q('#cert-code').value||null,issued_at:q('#cert-issued').value||null,expires_at:q('#cert-expires').value||null,pdf_url:q('#cert-pdf').value||null,notes:q('#cert-notes').value||null,last_checked_at:new Date().toISOString(),source:'registro manual'}).eq('id',q('#cert-id').value)}
  window.certificatesPage=render;window.AtlasCertificates={render,TYPES};
})();
