(() => {
 const C=window.AtlasV4Core;
 const safeEsc=v=>typeof esc==='function'?esc(v):String(v??'').replace(/[&<>"']/g,'');
 const cash=v=>typeof money==='function'?money(v):new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}).format(Number(v)||0);
 const dateBR=v=>typeof fmtDateBR==='function'?fmtDateBR(v):v?new Date(`${v}T12:00:00`).toLocaleDateString('pt-BR'):'—';
 const role=()=>window.atlasCurrentProfile?.role||'cliente';
 const profile=()=>window.atlasCurrentProfile||{};
 function sectionsForRole(r){return ({admin:{operation:true,financial:true,executive:true,editable:true},operacao:{operation:true,financial:true,executive:false,editable:true},financeiro:{operation:false,financial:true,executive:false,editable:true},cliente:{operation:true,financial:false,executive:false,editable:false},auditoria:{operation:true,financial:true,executive:true,editable:false}})[r]||{operation:false,financial:false,executive:false,editable:false};}
 window.AtlasV4Dashboard={sectionsForRole};
 function company(data,p){return typeof clientNameById==='function'?clientNameById(data.clients,p.client_id):(data.clients||[]).find(c=>c.id===p.client_id)?.legal_name||p.client||'—';}
 function stage(p){return p.stage_name||p.current_stage_name||p.current_stage?.name||p.stage||'—';}
 function nextAction(p){return p.next_action||p.next_step||p.pending_action||'Definir próxima ação';}
 function statusText(p){return p.status_label||p.status||'Em andamento';}
 function initials(v){return String(v||'—').split(/\s+/).filter(Boolean).slice(0,2).map(x=>x[0]).join('').toUpperCase();}
 function deadlineBadge(p){const s=p._deadlineState||C.classifyDeadline(p);const map={overdue:['Atrasado','critical'],today:['Hoje','critical'],tomorrow:['Amanhã','warn'],upcoming:[dateBR(p.due_date),'neutral'],none:['Sem prazo','neutral']};const [t,c]=map[s]||map.none;return `<span class="v4-badge ${c}">${safeEsc(t)}</span>`;}
 function kpi(label,value,sub,kind='',icon=''){return `<article class="v4-kpi ${kind}"><div class="v4-kpi-copy"><span>${label}</span><strong>${value}</strong><small>${sub}</small></div><div class="v4-kpi-icon">${icon}</div></article>`;}
 function queueTable(data,queue){if(!queue.length)return '<div class="v4-empty">Nenhum processo exige atenção imediata.</div>';return `<div class="v4-table-scroll"><table class="v4-ops-table"><thead><tr><th>Prioridade</th><th>Processo</th><th>Empresa</th><th>Etapa atual</th><th>Prazo</th><th>Responsável</th><th>Próxima ação</th><th>Ações</th></tr></thead><tbody>${queue.slice(0,8).map(p=>{const ds=p._deadlineState||C.classifyDeadline(p);const pri=ds==='overdue'||ds==='today'?['Crítica','critical']:String(p.priority||'').toLowerCase()==='high'?['Alta','warn']:['Normal','neutral'];const owner=p.owner_name||p.owner||p.responsible_name||'—';return `<tr><td><span class="v4-badge ${pri[1]}">● ${pri[0]}</span></td><td><strong>${safeEsc(p.public_code||p.id||'—')}</strong></td><td>${safeEsc(company(data,p))}</td><td><strong>${safeEsc(stage(p))}</strong><small class="v4-row-sub">${safeEsc(statusText(p))}</small></td><td>${deadlineBadge(p)}</td><td><span class="v4-owner"><i>${initials(owner)}</i>${safeEsc(owner)}</span></td><td>${safeEsc(nextAction(p))}</td><td>${C.canEditForRole(role())?`<button class="mini-btn" onclick="openAtlasV4Process('${safeEsc(p.id)}')">Abrir</button>`:'<span class="muted">Consulta</span>'}</td></tr>`;}).join('')}</tbody></table></div>`;}
 function health(procs){const active=procs.filter(p=>!['completed','cancelled'].includes(String(p.status||'').toLowerCase()));const total=active.length||1;const overdue=active.filter(p=>C.classifyDeadline(p)==='overdue').length;const attention=active.filter(p=>['today','tomorrow'].includes(C.classifyDeadline(p))).length;const ok=Math.max(0,active.length-overdue-attention);const pct=n=>Math.round(n/total*100);const stages=['Viabilidade','DBE','JUCESP','Prefeitura','Licenciamento'];const vals=stages.map(s=>{const a=active.filter(p=>stage(p).toLowerCase().includes(s.toLowerCase()));if(!a.length)return 0;const avg=a.map(p=>Number(p.days_in_stage||p.stage_days||0)).filter(Number.isFinite);return avg.length?Math.max(.5,avg.reduce((x,y)=>x+y,0)/avg.length):Math.max(1,a.length);});const max=Math.max(...vals,1);return `<section class="v4-card v4-health"><div class="v4-section-head"><h2>Saúde da Operação</h2><select class="v4-period"><option>Últimos 30 dias</option></select></div><div class="v4-health-top"><div class="v4-health-ring" style="--ok:${pct(ok)};--attention:${pct(attention)}"><div><strong>${active.length}</strong><span>processos</span></div></div><div class="v4-health-legend"><div><i class="ok"></i><span>No prazo</span><b>${pct(ok)}%</b></div><div><i class="attention"></i><span>Em atenção</span><b>${pct(attention)}%</b></div><div><i class="late"></i><span>Atrasados</span><b>${pct(overdue)}%</b></div></div></div><h3>Tempo médio por etapa (dias)</h3><div class="v4-stage-bars">${stages.map((s,i)=>`<div><span>${s}</span><em><i style="width:${Math.round(vals[i]/max*100)}%"></i></em><b>${vals[i]?vals[i].toFixed(1).replace('.',','):'—'}</b></div>`).join('')}</div></section>`;}
 function pipeline(procs){const stages=['Entrada','Documentação','Viabilidade','DBE','Junta/Cartório','Prefeitura','Licenças','Conclusão'];const counts=Object.fromEntries(stages.map(s=>[s,0]));for(const p of procs){const st=stage(p).toLowerCase();let k=stages.find(x=>st.includes(x.toLowerCase().split('/')[0]));if(!k){if(/conclu|completed/.test(String(p.status||'').toLowerCase()))k='Conclusão';else k='Entrada';}counts[k]++;}return `<section class="v4-card v4-pipeline"><div class="v4-section-head"><h2>Pipeline de Processos</h2><select class="v4-period"><option>Todos os tipos</option></select></div><div class="v4-pipeline-track">${stages.map((s,i)=>`<div class="v4-pipe-step"><span>${i+1}</span><small>${s}</small><strong>${counts[s]}</strong></div>`).join('')}</div></section>`;}
 function pendingCard(data){const p=C.buildPendingSummary(data);return `<section class="v4-card v4-pending"><div class="v4-section-head"><h2>Central de Pendências</h2><button class="v4-link" onclick="document.querySelector('[data-page=processos]')?.click()">Ver todas</button></div><div class="v4-pending-grid"><div><i>●</i><span>Clientes<small>Aguardando documento</small></span><strong>${p.cliente}</strong></div><div><i>●</i><span>Financeiro<small>Pagamentos pendentes</small></span><strong>${p.financeiro}</strong></div><div><i>●</i><span>Equipe<small>Ações pendentes</small></span><strong>${p.equipe}</strong></div><div><i>●</i><span>Licenças<small>Renovações necessárias</small></span><strong>${p.licencas}</strong></div><div><i>●</i><span>Órgãos<small>Aguardando análise</small></span><strong>${p.orgao}</strong></div></div></section>`;}
 function licenseCard(b){return `<section class="v4-card v4-licenses"><div class="v4-section-head"><h2>Central de Licenças</h2><button class="v4-link" onclick="document.querySelector('[data-page=licencas]')?.click()">Ver todas</button></div><div class="v4-license-list"><div><span><i class="late">✓</i>Vencidas</span><strong>${b.vencidas.length}</strong></div><div><span><i class="attention">✓</i>Até 30 dias</span><strong>${b.ate30.length}</strong></div><div><span><i class="attention">✓</i>31 – 60 dias</span><strong>${b.d31a60.length}</strong></div><div><span><i class="ok">✓</i>Regulares</span><strong>${b.regulares.length}</strong></div></div></section>`;}
 window.openAtlasV4Process=function(id){if(typeof window.openProcessDetail==='function')return window.openProcessDetail(id);if(typeof window.openProcessModal==='function')return window.openProcessModal(id);document.querySelector('[data-page="processos"]')?.click();};
 window.dashboard=async function(){setHead('Dashboard','VISÃO GERAL','');page('<div class="loading-box"><span class="spinner"></span><div>Carregando operação...</div></div>');const raw=await loadOperationalData();const procs=decorateProcesses(raw);const data={...raw,processes:procs};const m=C.buildDashboardMetrics(data);const queue=C.buildTodayQueue(procs);const b=C.bucketLicenses(data.licenses||[]);const cfg=sectionsForRole(role());const user=profile().full_name||profile().name||document.querySelector('#user-name')?.textContent||'Usuário';const first=user.split(/\s+/)[0]||'Usuário';const label={admin:'Administrador',operacao:'Operação',financeiro:'Financeiro',cliente:'Cliente',auditoria:'Auditoria'}[role()]||role();const opKpis=cfg.operation?kpi('Processos ativos',m.active,'↗ +3 nesta semana','','▤')+kpi('Atrasados',m.overdue,'● Requer ação','danger','△')+kpi('Pendências de cliente',m.pendingClient,'● Aguardando documentos','','●')+kpi('Licenças ≤ 30 dias',m.licenses30,`${b.vencidas.length} vencida(s)`,'warn','✓'):'';const finKpis=cfg.financial?kpi('Honorários a receber',cash(m.honorariosAReceber),'Saldo pendente','money','$')+kpi('Taxas a pagar',cash(m.taxasAPagar),'Saldo pendente','','▣'):'';page(`<div class="v4-dashboard"><div class="v4-top-intro"><div><h1>Olá, ${safeEsc(first)}! <span>👋</span></h1><p>Aqui está o que precisa da sua atenção hoje.</p></div><select class="v4-profile-select" aria-label="Meu painel"><option>Meu painel (${safeEsc(label)})</option></select></div><div class="v4-kpis">${opKpis}${finKpis}</div>${cfg.operation?`<div class="v4-main-grid"><section class="v4-card v4-today"><div class="v4-section-head"><div><h2>Minha Operação Hoje <span class="v4-count">${queue.length}</span></h2><span>Tarefas e processos que precisam de atenção</span></div><div class="v4-head-actions"><button class="v4-link" onclick="document.querySelector('[data-page=processos]')?.click()">Ver todos</button>${cfg.editable?'<button class="btn btn-primary" onclick="document.querySelector(\'#new-process-btn\')?.click()">＋ Novo processo</button>':''}</div></div>${queueTable(data,queue)}</section>${health(procs)}</div><div class="v4-bottom-grid">${pipeline(procs)}${pendingCard(data)}${licenseCard(b)}</div>`:''}${cfg.financial&&!cfg.operation?`<div class="v4-finance-only">${pendingCard(data)}</div>`:''}</div>`);};
})();
