(() => {
 const C=window.AtlasV4Core;
 const safeEsc=v=>typeof esc==='function'?esc(v):String(v??'').replace(/[&<>"']/g,'');
 const cash=v=>typeof money==='function'?money(v):new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}).format(Number(v)||0);
 const dateBR=v=>typeof fmtDateBR==='function'?fmtDateBR(v):v?new Date(v+'T12:00:00').toLocaleDateString('pt-BR'):'—';
 const role=()=>window.atlasCurrentProfile?.role||'cliente';
 function sectionsForRole(r){return ({admin:{operation:true,financial:true,executive:true,editable:true},operacao:{operation:true,financial:false,executive:false,editable:true},financeiro:{operation:false,financial:true,executive:false,editable:true},cliente:{operation:true,financial:false,executive:false,editable:false},auditoria:{operation:true,financial:true,executive:true,editable:false}})[r]||{operation:false,financial:false,executive:false,editable:false};}
 window.AtlasV4Dashboard={sectionsForRole};
 function company(data,p){return typeof clientNameById==='function'?clientNameById(data.clients,p.client_id):(data.clients||[]).find(c=>c.id===p.client_id)?.legal_name||p.client||'—';}
 function stage(p){return p.stage_name||p.current_stage_name||p.current_stage?.name||p.stage||'—';}
 function nextAction(p){return p.next_action||p.next_step||p.pending_action||'Definir próxima ação';}
 function statusText(p){return p.status_label||p.status||'Em andamento';}
 function deadlineBadge(p){const s=p._deadlineState||C.classifyDeadline(p);const map={overdue:['Atrasado','critical'],today:['Hoje','critical'],tomorrow:['Amanhã','warn'],upcoming:[dateBR(p.due_date),'neutral'],none:['Sem prazo','neutral']};const [t,c]=map[s]||map.none;return `<span class="v4-badge ${c}">${safeEsc(t)}</span>`;}
 function kpi(label,value,sub,kind=''){return `<article class="v4-kpi ${kind}"><span>${label}</span><strong>${value}</strong><small>${sub}</small></article>`;}
 function queueTable(data,queue){
  if(!queue.length)return '<div class="v4-empty">Nenhum processo exige atenção imediata.</div>';
  return `<div class="v4-table-scroll"><table class="v4-ops-table"><thead><tr><th>Prioridade</th><th>Processo</th><th>Empresa</th><th>Etapa atual</th><th>Prazo</th><th>Responsável</th><th>Próxima ação</th><th>Ações</th></tr></thead><tbody>${queue.slice(0,8).map(p=>`<tr><td>${p._deadlineState==='overdue'?'<span class="v4-badge critical">Crítica</span>':String(p.priority||'').toLowerCase()==='high'?'<span class="v4-badge warn">Alta</span>':'<span class="v4-badge neutral">Normal</span>'}</td><td><strong>${safeEsc(p.public_code||p.id||'—')}</strong></td><td>${safeEsc(company(data,p))}</td><td><strong>${safeEsc(stage(p))}</strong><small class="v4-row-sub">${safeEsc(statusText(p))}</small></td><td>${deadlineBadge(p)}</td><td>${safeEsc(p.owner_name||p.owner||p.responsible_name||'—')}</td><td>${safeEsc(nextAction(p))}</td><td>${C.canEditForRole(role())?`<button class="mini-btn" onclick="openAtlasV4Process('${safeEsc(p.id)}')">Abrir</button>`:'<span class="muted">Consulta</span>'}</td></tr>`).join('')}</tbody></table></div>`;
 }
 function health(procs){const active=procs.filter(p=>!['completed','cancelled'].includes(String(p.status||'').toLowerCase()));const total=active.length||1;const overdue=active.filter(p=>C.classifyDeadline(p)==='overdue').length;const attention=active.filter(p=>['today','tomorrow'].includes(C.classifyDeadline(p))).length;const ok=Math.max(0,active.length-overdue-attention);const pct=n=>Math.round(n/total*100);return `<section class="v4-card v4-health"><div class="v4-section-head"><h2>Saúde da Operação</h2><span>Visão atual</span></div><div class="v4-health-ring" style="--ok:${pct(ok)};--attention:${pct(attention)}"><div><strong>${active.length}</strong><small>processos</small></div></div><div class="v4-health-legend"><div><i class="ok"></i><span>No prazo</span><strong>${pct(ok)}%</strong></div><div><i class="attention"></i><span>Em atenção</span><strong>${pct(attention)}%</strong></div><div><i class="late"></i><span>Atrasados</span><strong>${pct(overdue)}%</strong></div></div></section>`;}
 function pipeline(procs){const stages=['Entrada','Documentação','Viabilidade','DBE','Junta/Cartório','Prefeitura','Licenças','Conclusão'];const counts=Object.fromEntries(stages.map(s=>[s,0]));for(const p of procs){const t=String(stage(p)).toLowerCase();let key=t.includes('brief')||t.includes('entrada')?'Entrada':t.includes('doc')?'Documentação':t.includes('viab')?'Viabilidade':t.includes('dbe')||t.includes('receita')?'DBE':t.includes('junta')||t.includes('cart')||t.includes('registro')?'Junta/Cartório':t.includes('pref')||t.includes('inscri')?'Prefeitura':t.includes('licen')?'Licenças':String(p.status)==='completed'?'Conclusão':'Entrada';counts[key]++;}return `<section class="v4-card v4-pipeline"><div class="v4-section-head"><h2>Pipeline de Processos</h2><span>${procs.length} processos</span></div><div class="v4-pipeline-row">${stages.map((s,i)=>`<div class="v4-pipeline-step"><span>${s}</span><strong>${counts[s]}</strong>${i<stages.length-1?'<i>→</i>':''}</div>`).join('')}</div></section>`;}
 function pendingCard(data){const p=C.buildPendingSummary(data);return `<section class="v4-card"><div class="v4-section-head"><h2>Central de Pendências</h2><span>Por origem</span></div><div class="v4-summary-list"><div><span>Clientes<small>Aguardando documento/retorno</small></span><strong>${p.cliente}</strong></div><div><span>Equipe<small>Ações internas pendentes</small></span><strong>${p.equipe}</strong></div><div><span>Órgãos<small>Aguardando análise</small></span><strong>${p.orgao}</strong></div><div><span>Financeiro<small>Pagamentos pendentes</small></span><strong>${p.financeiro}</strong></div><div><span>Licenças<small>Renovações necessárias</small></span><strong>${p.licencas}</strong></div></div></section>`;}
 function licenseCard(b){return `<section class="v4-card"><div class="v4-section-head"><h2>Central de Licenças</h2><span>Vencimentos</span></div><div class="v4-summary-list v4-license-list"><div><span>Vencidas</span><strong class="danger">${b.vencidas.length}</strong></div><div><span>Até 30 dias</span><strong>${b.ate30.length}</strong></div><div><span>31 – 60 dias</span><strong>${b.d31a60.length}</strong></div><div><span>61 – 90 dias</span><strong>${b.d61a90.length}</strong></div><div><span>Regulares</span><strong class="success">${b.regulares.length}</strong></div></div></section>`;}
 window.openAtlasV4Process=function(id){if(typeof window.openProcessDetail==='function')return window.openProcessDetail(id);if(typeof window.openProcessModal==='function')return window.openProcessModal(id);const btn=document.querySelector('[data-page="processos"]');btn?.click();};
 window.dashboard=async function(){
  setHead('Dashboard','VISÃO GERAL','Aqui está o que precisa da sua atenção hoje.');
  page('<div class="loading-box"><span class="spinner"></span><div>Carregando cockpit operacional...</div></div>');
  const raw=await loadOperationalData(); const procs=decorateProcesses(raw); const data={...raw,processes:procs};
  const m=C.buildDashboardMetrics(data); const queue=C.buildTodayQueue(procs); const b=m.licenseBuckets;
  const cfg=sectionsForRole(role());
  const opKpis=cfg.operation?kpi('Processos ativos',m.active,'Fluxos em andamento')+kpi('Atrasados',m.overdue,'Requer ação','danger')+kpi('Pendências de cliente',m.pendingClient,'Aguardando retorno')+kpi('Licenças ≤ 30 dias',m.licenses30,`${b.vencidas.length} vencida(s)`,'warn'):'';
  const finKpis=cfg.financial?kpi('Honorários a receber',cash(m.honorariosAReceber),'Saldo pendente')+kpi('Taxas a pagar',cash(m.taxasAPagar),'Saldo pendente'):'';
  const operation=cfg.operation?`<div class="v4-main-grid"><section class="v4-card v4-today"><div class="v4-section-head"><div><h2>Minha Operação Hoje <span class="v4-count">${queue.length}</span></h2><span>Tarefas e processos que precisam de atenção</span></div>${cfg.editable?'<button class="btn btn-primary" onclick="document.querySelector(\'[data-page=processos]\')?.click()">Ver processos</button>':''}</div>${queueTable(data,queue)}</section>${health(procs)}</div><div class="v4-bottom-grid">${pipeline(procs)}${pendingCard(data)}${licenseCard(b)}</div>`:'';
  const financeOnly=cfg.financial&&!cfg.operation?`<section class="v4-card"><div class="v4-section-head"><h2>Financeiro</h2><span>Visão de recebimentos e pagamentos</span></div><div class="v4-summary-list"><div><span>Honorários a receber</span><strong>${cash(m.honorariosAReceber)}</strong></div><div><span>Taxas a pagar</span><strong>${cash(m.taxasAPagar)}</strong></div></div></section>`:'';
  page(`<div class="v4-dashboard"><div class="v4-kpis">${opKpis}${finKpis}</div>${operation}${financeOnly}</div>`);
 };
})();
