(() => {
  const CONFIG_URL="https://fwkaxfamhuiabbwzltsn.supabase.co/functions/v1/atlas-browser-config";
  const USERS_URL="https://fwkaxfamhuiabbwzltsn.supabase.co/functions/v1/atlas-lawyer-users";
  const ORG_ID="11111111-1111-4111-8111-111111111111";
  let sb=null,currentProfile=null,currentMember=null;
  const q=id=>document.getElementById(id);
  const msg=(el,text,kind="info")=>{if(!el)return;el.textContent=text||"";el.className="auth-message"+(text?" "+kind:" hidden")};
  const show=name=>["login","bootstrap"].forEach(v=>q("auth-"+v+"-view")?.classList.toggle("hidden",v!==name));
  const friendly=e=>{const s=String(e?.message||e||"");if(/Invalid login/i.test(s))return"E-mail ou senha inválidos.";if(/BOOTSTRAP_CLOSED/i.test(s))return"A primeira ativação já foi concluída.";return s||"Não foi possível concluir a operação."};
  async function initClient(){const r=await fetch(CONFIG_URL,{cache:"no-store"});const c=await r.json();if(!r.ok||!c.url||!c.key)throw new Error(c.error||"Configuração do Supabase indisponível.");sb=window.supabase.createClient(c.url,c.key,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true}})}
  async function bootstrapStatus(){const {data,error}=await sb.rpc("atlas_lawyer_bootstrap_status");if(error)throw error;const a=!!data?.available;q("first-access-btn")?.classList.toggle("hidden",!a);q("auth-status-dot")?.classList.add("ok");q("auth-status-text").textContent=a?"Ambiente conectado · aguardando primeira ativação":"Ambiente conectado · autenticação ativa"}
  async function profile(uid){const [p,m]=await Promise.all([sb.from("profiles").select("id,full_name,email").eq("id",uid).maybeSingle(),sb.from("organization_members").select("role,active").eq("org_id",ORG_ID).eq("user_id",uid).maybeSingle()]);if(p.error)throw p.error;if(m.error)throw m.error;return{profile:p.data,member:m.data}}
  async function handle(session){if(!session?.user){q("login-screen").classList.remove("hidden");q("app-shell").classList.add("hidden");return}const x=await profile(session.user.id);if(!x.profile||!x.member?.active){await sb.auth.signOut();msg(q("login-message"),"Conta sem acesso ativo. Procure o Administrador.","error");return}currentProfile=x.profile;currentMember=x.member;q("login-screen").classList.add("hidden");window.showApp?.({...x.profile,role:x.member.role})}
  async function bootstrap(payload){const r=await fetch(USERS_URL,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"bootstrap",...payload})});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||"Falha na ativação.");return d}
  async function adminRequest(payload){const {data:{session}}=await sb.auth.getSession();if(!session)throw new Error("Sessão expirada.");const r=await fetch(USERS_URL,{method:"POST",headers:{"Content-Type":"application/json","Authorization":"Bearer "+session.access_token},body:JSON.stringify(payload)});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||"Falha na administração de usuários.");return d}
  async function init(){await initClient();document.querySelectorAll("[data-auth-view]").forEach(b=>b.onclick=()=>show(b.dataset.authView));q("first-access-btn").onclick=()=>show("bootstrap");q("logout-btn").onclick=()=>sb.auth.signOut();
    q("login-form").onsubmit=async e=>{e.preventDefault();msg(q("login-message"),"");const btn=q("login-submit");btn.disabled=true;try{const {data,error}=await sb.auth.signInWithPassword({email:q("login-email").value.trim(),password:q("login-password").value});if(error)throw error;await handle(data.session)}catch(err){msg(q("login-message"),friendly(err),"error")}finally{btn.disabled=false}};
    q("bootstrap-form").onsubmit=async e=>{e.preventDefault();msg(q("bootstrap-message"),"");const pass=q("bootstrap-password").value;if(pass!==q("bootstrap-confirm").value)return msg(q("bootstrap-message"),"As senhas não coincidem.","error");if(pass.length<10)return msg(q("bootstrap-message"),"Use ao menos 10 caracteres.","error");const btn=q("bootstrap-submit");btn.disabled=true;try{const email=q("bootstrap-email").value.trim();await bootstrap({fullName:q("bootstrap-name").value.trim(),email,password:pass});const {data,error}=await sb.auth.signInWithPassword({email,password:pass});if(error)throw error;await bootstrapStatus();await handle(data.session)}catch(err){msg(q("bootstrap-message"),friendly(err),"error")}finally{btn.disabled=false}};
    sb.auth.onAuthStateChange(async(e,s)=>{if(e==="SIGNED_OUT"){currentProfile=null;currentMember=null;q("app-shell").classList.add("hidden");q("login-screen").classList.remove("hidden");show("login")}else if(e==="SIGNED_IN"&&s)await handle(s)});
    await bootstrapStatus();const {data:{session}}=await sb.auth.getSession();if(session)await handle(session)
  }
  window.atlasAuth={get client(){return sb},getProfile:()=>currentProfile,getMember:()=>currentMember,adminRequest,roleLabel:r=>({admin:"Administrador",socio:"Sócio",advogado:"Advogado",controladoria:"Controladoria",estagiario:"Estagiário",financeiro:"Financeiro",viewer:"Consulta"})[r]||r};
  init().catch(e=>{console.error(e);q("auth-status-text").textContent="Falha ao conectar o ambiente";msg(q("login-message"),friendly(e),"error")});
})();