(() => {
 const C=window.AtlasV4Core;
 let mode='list';
 const role=()=>window.atlasCurrentProfile?.role||'cliente';
 const e=v=>typeof esc==='function'?esc(v):String(v??'');
 const d=v=>typeof fmtDateBR==='function'?fmtDateBR(v):(v||'—');
 const entityText=(v,keys=[])=>{if(v==null)return '';if(typeof v==='string'||typeof v==='number')return String(v);for(const k of keys){if(v?.[k]!=null&&typeof v[k]!=='object')return String(v[k]);}return '';};
 const labelize=v=>String(v??'').replace(/_/g,' ').replace(/\b\w/g,c=>c.toUpperCase());
 const company=(data,p)=>{const linked=typeof clientNameById==='function'?clientNameById(data.clients,p.client_id):(data.clients||[]).find(c=>c.id===p.client_id)?.legal_name;return linked||entityText(p.client,['legal_name','trade_name','name'])||'—';};
 const stage=p=>entityText(p.stage_name||p.current_stage_name||p.current_stage||p.stage,['name','label','title'])||'—';
 const owner=p=>entityText(p.owner_name||p.responsible_name||p.owner,['full_name','name','label'])||'—';
 const next=p=>entityText(p.next_action||p.next_step||p.pending_action,['name','label','title'])||'Definir próxima ação';
 function canEditForRole(r){return C.canEditForRole(r)&&!['cliente','auditoria'].includes(r);}
 function actions(p){return canEditForRole(role())?`<button class="mini-btn" onclick="openAtlasV4Process('${e(p.id)}')">Abrir</button>`:'<span class="muted">Consulta</span>';}
 function filters(procs){const owners=[...new Set(procs.map(owner).filter(v=>v&&v!=='—'))].sort((a,b)=>a.localeCompare(b,'pt-BR'));return `<div class="v4-process-toolbar"><div class="v4-view-toggle"><button data-v4-view="list" class="${mode==='list'?'active':''}">Lista</button><button data-v4-view="pipeline" class="${mode==='pipeline'?'active':''}">Pipeline</button></div><div class="v4-filter-row"><select id="v4-status-filter"><option value="">Todos os status</option><option value="overdue">Atrasados</option><option value="today">Vencem hoje</option><option value="pending">Pendência</option></select><select id="v4-owner-filter"><option value="">Todos responsáveis</option>${owners.map(o=>`<option>${e(o)}</option>`).join('')}</select></div></div>`;}
 function list(data,procs){if(!procs.length)return '<div class="v4-empty">Nenhum processo encontrado.</div>';return `<div class="v4-process-list"><div class="v4-process-head"><span>Processo</span><span>Empresa</span><span>Tipo</span><span>Etapa</span><span>Responsável</span><span>Prazo</span><span>Status</span><span>Próxima ação</span><span></span></div>${procs.map(p=>`<article class="v4-process-row" data-deadline="${C.classifyDeadline(p)}" data-owner="${e(owner(p)==='—'?'':owner(p))}"><div><strong>${e(p.public_code||p.id||'—')}</strong></div><div>${e(company(data,p))}</div><div>${e(labelize(p.service_type||p.title||'—'))}</div><div>${e(stage(p))}</div><div>${e(owner(p))}</div><div>${d(p.due_date)}</div><div><span class="v4-badge ${C.classifyDeadline(p)==='overdue'?'critical':'neutral'}">${e(labelize(p.status_label||p.status||'Em andamento'))}</span></div><div>${e(next(p))}</div><div>${actions(p)}</div></article>`).join('')}</div>`;}
 function pipeline(data,procs){const groups=new Map();for(const p of procs){const k=stage(p);if(!groups.has(k))groups.set(k,[]);groups.get(k).push(p);}return `<div class="v4-process-pipeline">${[...groups.entries()].map(([s,arr])=>`<section class="v4-pipe-col"><header><strong>${e(s)}</strong><span>${arr.length}</span></header>${arr.map(p=>`<article><b>${e(p.public_code||p.id||'—')}</b><strong>${e(company(data,p))}</strong><small>${e(labelize(p.title||p.service_type||''))}</small><div>${d(p.due_date)} · ${e(owner(p))}</div>${actions(p)}</article>`).join('')}</section>`).join('')}</div>`;}
 function bind(data,procs){document.querySelectorAll('[data-v4-view]').forEach(b=>b.onclick=()=>{mode=b.dataset.v4View;renderBody(data,procs)});const sf=document.querySelector('#v4-status-filter'),of=document.querySelector('#v4-owner-filter');const apply=()=>{document.querySelectorAll('.v4-process-row').forEach(r=>{const okS=!sf?.value||(sf.value==='pending'?/pend/i.test(r.textContent):r.dataset.deadline===sf.value);const okO=!of?.value||r.dataset.owner===of.value;r.hidden=!(okS&&okO);});};sf?.addEventListener('change',apply);of?.addEventListener('change',apply);}
 function renderBody(data,procs){const host=document.querySelector('#v4-process-body');if(!host)return;host.innerHTML=filters(procs)+(mode==='list'?list(data,procs):pipeline(data,procs));bind(data,procs);}
 window.processPage=async function(){setHead('Processos','OPERAÇÃO','Gerencie prazos, responsáveis, etapas e próximas ações.');page('<div class="loading-box"><span class="spinner"></span><div>Carregando processos...</div></div>');const raw=await loadOperationalData();const procs=decorateProcesses(raw);page('<section class="v4-card"><div class="v4-section-head"><div><h2>Operação de Legalização</h2><span>Lista operacional e Pipeline</span></div></div><div id="v4-process-body"></div></section>');renderBody({...raw,processes:procs},procs);};
 async function exigenciasPage(){
  setHead('Exigências','OPERAÇÃO','Acompanhe exigências e pendências formais registradas nos processos.');
  page('<div class="loading-box"><span class="spinner"></span><div>Carregando exigências...</div></div>');
  const raw=await loadOperationalData(); const procs=decorateProcesses(raw);
  const items=procs.filter(p=>/exig|pend/i.test([p.status,p.status_label,p.notes,p.title,p.next_action,p.pending_action].filter(Boolean).join(' ')));
  page(`<section class="v4-card"><div class="v4-section-head"><div><h2>Central de Exigências</h2><span>${items.length} registro(s) identificado(s)</span></div></div>${items.length?`<div class="v4-exigencias">${items.map(p=>`<article class="v4-exigencia-item"><div><strong>${e(p.public_code||p.id||'—')} · ${e(company(raw,p))}</strong><small>${e(labelize(p.status_label||p.status||'Pendência'))} · ${e(labelize(p.title||p.service_type||''))}</small></div><div>${canEditForRole(role())?`<button class="mini-btn" onclick="openAtlasV4Process('${e(p.id)}')">Abrir</button>`:'<span class="muted">Consulta</span>'}</div></article>`).join('')}</div>`:'<div class="v4-empty">Nenhuma exigência ou pendência formal identificada nos dados atuais.</div>'}</section>`);
 }
 const legacyRender=window.render;
 if(typeof legacyRender==='function'){window.render=function(pageName){if(pageName==='exigencias')return exigenciasPage();return legacyRender(pageName);};}
 window.AtlasV4Operations={canEditForRole};
})();
