(() => {
 const C=window.AtlasV4Core;
 let mode='list';
 const currentProfile=()=>window.atlasCurrentProfile||window.atlasAuth?.getProfile?.()||{};
 const role=()=>currentProfile().role||'cliente';
 const e=v=>typeof esc==='function'?esc(v):String(v??'');
 const d=v=>typeof fmtDateBR==='function'?fmtDateBR(v):(v||'—');
 const entityText=(v,keys=[])=>{if(v==null)return '';if(typeof v==='string'||typeof v==='number')return String(v);for(const k of keys){if(v?.[k]!=null&&typeof v[k]!=='object')return String(v[k]);}return '';};
 const labelize=v=>String(v??'').replace(/_/g,' ').replace(/\b\w/g,c=>c.toUpperCase());
 const company=(data,p)=>{const linked=typeof clientNameById==='function'?clientNameById(data.clients,p.client_id):(data.clients||[]).find(c=>c.id===p.client_id)?.legal_name;return linked||entityText(p.client,['legal_name','trade_name','name'])||'—';};
 const stage=p=>entityText(p.stage_name||p.current_stage_name||p.current_stage||p.stage,['name','label','title'])||'—';
 const owner=p=>entityText(p.owner_name||p.responsible_name||p.owner,['full_name','name','label'])||'—';
 const next=p=>entityText(p.next_action||p.next_step||p.pending_action,['name','label','title'])||'Definir próxima ação';
 function canEditForRole(r){return C.canEditForRole(r)&&!['cliente','auditoria'].includes(r);}
 function bucket(p){const st=stage(p).toLowerCase();if(/conclu/.test(st)||String(p.status||'').toLowerCase()==='completed')return 'Conclusão';if(/document/.test(st))return 'Documentação';if(/viabil/.test(st))return 'Viabilidade';if(/dbe|receita/.test(st))return 'DBE';if(/junta|cart[oó]rio/.test(st))return 'Junta/Cartório';if(/prefeitura|inscri/.test(st))return 'Prefeitura';if(/licen/.test(st))return 'Licenças';if(/registro/.test(st))return 'Entrada';return 'Entrada';}
 function processId(p){return e(p.id||'');}
 function actions(p){
   if(!canEditForRole(role()))return '<span class="muted">Consulta</span>';
   const cart=String(p.status||'').toLowerCase()==='completed'?`<button class="mini-btn" type="button" onclick="emitirCartilha('${processId(p)}')">Emitir cartilha</button>`:'';
   return `<div class="v4-row-actions"><button class="mini-btn" type="button" onclick="openAtlasV4Process('${processId(p)}')">Abrir</button>${cart}</div>`;
 }
 function nextActionControl(p){return canEditForRole(role())?`<button type="button" class="v4-action-link" onclick="openAtlasV4Actions('${processId(p)}','${e(p.status||'')}')">${e(next(p))}</button>`:`<span>${e(next(p))}</span>`;}
 function filters(procs){const owners=[...new Set(procs.map(owner).filter(v=>v&&v!=='—'))].sort((a,b)=>a.localeCompare(b,'pt-BR'));return `<div class="v4-process-toolbar"><div class="v4-view-toggle"><button data-v4-view="list" class="${mode==='list'?'active':''}">Lista</button><button data-v4-view="pipeline" class="${mode==='pipeline'?'active':''}">Pipeline</button></div><div class="v4-filter-row"><select id="v4-status-filter"><option value="">Todos os status</option><option value="overdue">Atrasados</option><option value="today">Vencem hoje</option><option value="pending">Pendência</option></select><select id="v4-owner-filter"><option value="">Todos responsáveis</option>${owners.map(o=>`<option>${e(o)}</option>`).join('')}</select></div></div>`;}
 function list(data,procs){if(!procs.length)return '<div class="v4-empty">Nenhum processo encontrado.</div>';return `<div class="v4-process-list"><div class="v4-process-head"><span>Processo</span><span>Empresa</span><span>Tipo</span><span>Etapa</span><span>Responsável</span><span>Prazo</span><span>Status</span><span>Próxima ação</span><span></span></div>${procs.map(p=>`<article class="v4-process-row" data-deadline="${C.classifyDeadline(p)}" data-owner="${e(owner(p)==='—'?'':owner(p))}"><div><strong>${e(p.public_code||p.id||'—')}</strong></div><div>${e(company(data,p))}</div><div>${e(labelize(p.service_type||p.title||'—'))}</div><div>${e(stage(p))}</div><div>${e(owner(p))}</div><div>${d(p.due_date)}</div><div><span class="v4-badge ${C.classifyDeadline(p)==='overdue'?'critical':'neutral'}">${e(labelize(p.status_label||p.status||'Em andamento'))}</span></div><div>${nextActionControl(p)}</div><div>${actions(p)}</div></article>`).join('')}</div>`;}
 function pipeline(data,procs){const groups=new Map();for(const p of procs){const k=stage(p);if(!groups.has(k))groups.set(k,[]);groups.get(k).push(p);}return `<div class="v4-process-pipeline">${[...groups.entries()].map(([s,arr])=>`<section class="v4-pipe-col"><header><strong>${e(s)}</strong><span>${arr.length}</span></header>${arr.map(p=>`<article><b>${e(p.public_code||p.id||'—')}</b><strong>${e(company(data,p))}</strong><small>${e(labelize(p.title||p.service_type||''))}</small><div>${d(p.due_date)} · ${e(owner(p))}</div><div class="v4-pipe-actions">${nextActionControl(p)}${actions(p)}</div></article>`).join('')}</section>`).join('')}</div>`;}
 function bind(data,procs){document.querySelectorAll('[data-v4-view]').forEach(b=>b.onclick=()=>{mode=b.dataset.v4View;renderBody(data,procs)});const sf=document.querySelector('#v4-status-filter'),of=document.querySelector('#v4-owner-filter');const apply=()=>{document.querySelectorAll('.v4-process-row').forEach(r=>{const okS=!sf?.value||(sf.value==='pending'?/pend/i.test(r.textContent):r.dataset.deadline===sf.value);const okO=!of?.value||r.dataset.owner===of.value;r.hidden=!(okS&&okO);});};sf?.addEventListener('change',apply);of?.addEventListener('change',apply);}
 function renderBody(data,procs){const host=document.querySelector('#v4-process-body');if(!host)return;host.innerHTML=filters(procs)+(mode==='list'?list(data,procs):pipeline(data,procs));bind(data,procs);}
 window.processPage=async function(){setHead('Processos','OPERAÇÃO','Gerencie prazos, responsáveis, etapas e próximas ações.');page('<div class="loading-box"><span class="spinner"></span><div>Carregando processos...</div></div>');const raw=await loadOperationalData();const all=decorateProcesses(raw);const requested=window.atlasV4StageFilter||'';const procs=requested?all.filter(p=>bucket(p)===requested):all;window.atlasV4StageFilter=null;page(`<section class="v4-card"><div class="v4-section-head"><div><h2>Operação de Legalização</h2><span>${requested?`Filtro do Dashboard: ${e(requested)}`:'Lista operacional e Pipeline'}</span></div></div><div id="v4-process-body"></div></section>`);renderBody({...raw,processes:procs},procs);};
 async function exigenciasPage(){setHead('Exigências','OPERAÇÃO','Acompanhe exigências e pendências formais registradas nos processos.');page('<div class="loading-box"><span class="spinner"></span><div>Carregando exigências...</div></div>');const raw=await loadOperationalData();const procs=decorateProcesses(raw);const items=procs.filter(p=>/exig|pend/i.test([p.status,p.status_label,p.notes,p.title,p.next_action,p.pending_action].filter(Boolean).join(' ')));page(`<section class="v4-card"><div class="v4-section-head"><div><h2>Central de Exigências</h2><span>${items.length} registro(s) identificado(s)</span></div></div>${items.length?`<div class="v4-exigencias">${items.map(p=>`<article class="v4-exigencia-item"><div><strong>${e(p.public_code||p.id||'—')} · ${e(company(raw,p))}</strong><small>${e(labelize(p.status_label||p.status||'Pendência'))} · ${e(labelize(p.title||p.service_type||''))}</small></div><div>${actions(p)}</div></article>`).join('')}</div>`:'<div class="v4-empty">Nenhuma exigência ou pendência formal identificada nos dados atuais.</div>'}</section>`);}
 const legacyRender=window.render;if(typeof legacyRender==='function'){window.render=function(pageName){if(pageName==='exigencias')return exigenciasPage();return legacyRender(pageName);};}
 const legacyShowApp=window.showApp;if(typeof legacyShowApp==='function'){window.showApp=function(profile){window.atlasCurrentProfile=profile||window.atlasAuth?.getProfile?.()||{};return legacyShowApp(profile);};}
 window.openAtlasV4Process=(id)=>{const fn=window.openProcessModal||(typeof openProcessModal==='function'?openProcessModal:null);return fn?fn(id):null;};
 window.openAtlasV4Actions=(id,status)=>{if(!canEditForRole(role()))return;const completed=String(status||'').toLowerCase()==='completed';const body=`<div class="v4-action-menu"><button class="btn btn-primary" type="button" onclick="closeAtlasModal();openAtlasV4Process('${e(id)}')">Abrir / editar processo</button>${completed?`<button class="btn btn-muted" type="button" onclick="closeAtlasModal();emitirCartilha('${e(id)}')">Emitir cartilha</button>`:''}</div>`;const shell=window.modalShell||(typeof modalShell==='function'?modalShell:null);if(shell)shell('Ações do processo',body);else window.openAtlasV4Process(id);};
 window.openAtlasV4Stage=(stageName)=>{window.atlasV4StageFilter=stageName;document.querySelector('[data-page=processos]')?.click();};
 if(document?.addEventListener)document.addEventListener('click',ev=>{const step=ev.target.closest?.('.v4-pipeline-track .v4-pipe-step');if(step){const name=step.querySelector('small')?.textContent?.trim();if(name)window.openAtlasV4Stage(name);}});
 const style=document?.createElement?document.createElement('style'):null;if(style){style.id='atlas-v4-regression-fixes';style.textContent=`@media(max-width:1180px){.app-shell:not(.hidden){display:block!important;min-height:100vh!important}.workspace{margin-left:0!important;width:100%!important;min-width:0!important}.sidebar{width:min(86vw,292px)!important}}.atlas-modal{max-height:90vh!important;display:flex!important;flex-direction:column!important;overflow:hidden!important}.atlas-modal-body{overflow-y:auto!important;min-height:0!important;overscroll-behavior:contain}.v4-action-link{border:0;background:transparent;color:#0c4b82;font:inherit;font-weight:700;padding:0;text-align:left;cursor:pointer}.v4-action-link:hover{text-decoration:underline}.v4-row-actions,.v4-pipe-actions,.v4-action-menu{display:flex;gap:7px;align-items:center;flex-wrap:wrap}.v4-pipeline-track .v4-pipe-step{cursor:pointer}.v4-pipeline-track .v4-pipe-step:hover{border-color:#6ca7d0!important;box-shadow:0 0 0 3px rgba(27,101,151,.08)!important}@media(max-width:760px){.atlas-modal{max-height:94vh!important}}`;document.head?.appendChild(style);}
 function syncProfile(){const p=window.atlasAuth?.getProfile?.();if(!p)return false;const changed=!window.atlasCurrentProfile||window.atlasCurrentProfile.id!==p.id||window.atlasCurrentProfile.role!==p.role;window.atlasCurrentProfile=p;const logo=document.querySelector('.brand-logo');if(logo&&logo.src.indexOf('v=4.2')<0)logo.src='/atlas-sidebar-brand.svg?v=4.2';if(changed&&document.querySelector('[data-page=dashboard].active')&&typeof window.dashboard==='function')window.dashboard();return true;}
 if(document?.addEventListener){let tries=0;const timer=setInterval(()=>{tries++;if(syncProfile()||tries>20)clearInterval(timer);},250);document.addEventListener('DOMContentLoaded',()=>{syncProfile();const logo=document.querySelector('.brand-logo');if(logo)logo.src='/atlas-sidebar-brand.svg?v=4.2';});}
 window.AtlasV4Operations={canEditForRole};
})();
